
trigger:
  branches:
    include:
      - main
      - '*'
pool:
  name: FoodAppAgents
stages:
  - stage: "TestBuild"
    jobs:
      # - job: BackendTests
      #   timeoutInMinutes: "10"
      #   steps:
      #     - task: Maven@3
      #       inputs:
      #         mavenPomFile: backend/pom.xml
      #         mavenOptions: -Xmx3072m
      #         javaHomeOption: JDKVersion
      #         jdkArchitectureOption: x64
      #         publishJUnitResults: true
      #         testResultsFiles: "**/surefire-reports/TEST-*.xml"
      #         goals: package
      - job: Frontend
        steps:
          - script: |
              cd ./frontend
              npm ci
              ls -ltr
              pwd
              which npm
              npm test
          # - task: Npm@1
          #   displayName: npm run test
          #   inputs:
          #     command: "custom"
          #     workingDir:  "./frontend"
          #     customCommand: "test"

  # - stage: Deploy
  #   jobs:
  #     - job: Deploy_backend_to_azure
  #       steps:
  #         - script: echo "Coming Soon!"
