
trigger:
  branches:
    include:
      - main
      - '*'
pool:
  name: FoodAppAgents
stages:
  - stage: "TestBuild"
    jobs:
      - job: Mavenbuild
        steps:
          - task: Maven@3
            inputs:
              mavenPomFile: backend/pom.xml
              mavenOptions: -Xmx3072m
              javaHomeOption: JDKVersion
              jdkVersionOption: "1.17"
              jdkArchitectureOption: x64
              publishJUnitResults: true
              testResultsFiles: "**/surefire-reports/TEST-*.xml"
              goals: Package
  - stage: Deploy
    jobs:
      - job: Deploy_backend_to_azure
        steps:
          - script: echo "Coming Soon!"
