
trigger:
  branches:
    include:
      - main
      - '*'
pool:
  name: FoodAppAgents
stages:
  - stage: "TestBuild"
    jobs:
      - job: Backend
        steps:
          - task: Maven@3
            inputs:
              mavenPomFile: backend/pom.xml
              mavenOptions: -Xmx3072m
              javaHomeOption: JDKVersion
              jdkArchitectureOption: x64
              publishJUnitResults: true
              testResultsFiles: "**/surefire-reports/TEST-*.xml"
              goals: package
      - job: Frontend
        steps:
          - script: |
              cd frontend
              npm install
              npm test

  # - stage: Deploy
  #   jobs:
  #     - job: Deploy_backend_to_azure
  #       steps:
  #         - script: echo "Coming Soon!"
