
trigger:
  branches:
    include:
      - main
      - '*'
pool:
  name: FoodAppAgents
stages:
  - stage: "TestBuild"
    jobs:
      # - job: BackendTests
      #   timeoutInMinutes: "10"
      #   steps:
      #     - task: Maven@3
      #       inputs:
      #         mavenPomFile: backend/pom.xml
      #         mavenOptions: -Xmx3072m
      #         javaHomeOption: JDKVersion
      #         jdkArchitectureOption: x64
      #         publishJUnitResults: true
      #         testResultsFiles: "**/surefire-reports/TEST-*.xml"
      #         goals: package
      - job: Frontend
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '10.14.1'
            displayName: 'Install Node.js'

          - script: |
              npm install
              npm test
            displayName: 'npm install and test'

          - task: PublishTestResults@2
            condition: succeededOrFailed()
            inputs:
              testRunner: JUnit
              testResultsFiles: '**/TEST-RESULTS.xml'

          - task: ArchiveFiles@2
            displayName: 'Archive $(System.DefaultWorkingDirectory)'
            inputs:
              rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
              includeRootFolder: false
              archiveFile: '$(Build.ArtifactStagingDirectory)/node.zip'

          - task: PublishBuildArtifacts@1
            displayName: 'Publish Artifact: drop'
        # steps:
        #   - script: |
        #       cd ./frontend
        #       npm ci
        #       npm test

        #   - task: PublishTestResults@2
        #     displayName: 'Publish Unit Test Results'
        #     condition: succeededOrFailed()
        #     inputs:
        #         testResultsFormat: 'JUnit'
        #         testResultsFiles: '**/junit.xml'
        #         mergeTestResults: true
        #         failTaskOnFailedTests: true
        #         testRunTitle: 'React App Test'
