
trigger:
  branches:
    include:
      - main
      - '*'
pool:
  name: FoodAppAgents
stages:
  - stage: "TestBuild"
    jobs:
      # - job: BackendTests
      #   timeoutInMinutes: "10"
      #   steps:
      #     - task: Maven@3
      #       inputs:
      #         mavenPomFile: backend/pom.xml
      #         mavenOptions: -Xmx3072m
      #         javaHomeOption: JDKVersion
      #         jdkArchitectureOption: x64
      #         publishJUnitResults: true
      #         testResultsFiles: "**/surefire-reports/TEST-*.xml"
      #         goals: package
      - job: Frontend
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '20.11.0'
            displayName: 'Install Node.js'

          - script: echo $(Build.SourcesDirectory)

          - task: Npm@1
            displayName: 'Run Tests'
            inputs:
              command: 'custom'
              workingDir: $(Build.SourcesDirectory)/frontend
              customCommand: 'install'
          - task: Npm@1
            displayName: 'Run Tests'
            inputs:
              command: 'custom'
              workingDir: $(Build.SourcesDirectory)/frontend
              customCommand: 'test'

          - task: PublishTestResults@2
            displayName: 'Publish Unit Test Results'
            condition: succeededOrFailed()
            inputs:
              testResultsFormat: 'JUnit'
              testResultsFiles: '**/junit.xml'
              mergeTestResults: true
              failTaskOnFailedTests: true
              testRunTitle: 'React App Test'

        # steps:
        #   - script: |
        #       cd ./frontend
        #       npm ci
        #       npm test

        #   - task: PublishTestResults@2
        #     displayName: 'Publish Unit Test Results'
        #     condition: succeededOrFailed()
        #     inputs:
        #         testResultsFormat: 'JUnit'
        #         testResultsFiles: '**/junit.xml'
        #         mergeTestResults: true
        #         failTaskOnFailedTests: true
        #         testRunTitle: 'React App Test'
