INSERT INTO ITEMS (NAME, QUANTITY, UNIT) VALUES ('Item1', 10.0, 'kg');
INSERT INTO ITEMS (NAME, QUANTITY, UNIT) VALUES ('Item2', 15.0, 'kg');
INSERT INTO ITEMS (NAME, QUANTITY, UNIT) VALUES ('Item3', 20.0, 'kg');
