INSERT INTO ITEMS (NAME, QUANTITY, UNIT) VALUES ('Sausages', 12, 'pack');
INSERT INTO ITEMS (NAME, QUANTITY, UNIT) VALUES ('Eggs', 1, '12-pack');
INSERT INTO ITEMS (NAME, QUANTITY, UNIT) VALUES ('English Muffins', 3, 'packs');
INSERT INTO ITEMS (NAME, QUANTITY, UNIT) VALUES ('Orange Juice', 2, 'litres');
INSERT INTO ITEMS (NAME, QUANTITY, UNIT) VALUES ('Corriander', 1, 'large bunch');
INSERT INTO ITEMS (NAME, QUANTITY, UNIT) VALUES ('Cumin', 4, 'TBSP');
INSERT INTO ITEMS (NAME, QUANTITY, UNIT) VALUES ('Froozen Peas', 1, 'bag');
INSERT INTO ITEMS (NAME, QUANTITY, UNIT) VALUES ('Deoderant', 1, 'can');
